return {
    "stevearc/conform.nvim",
    lazy = true,
    opts = {
        formatters_by_ft = {
            astro = { "prettierd", "rustywind" },
            javascript = { "prettierd" },
            typ = { "typstyle" },
            typst = { "typstyle" },
            typescript = { "prettierd" },
            typescriptreact = { "prettierd" },
            json = { "prettierd" },
            jsonc = { "prettierd" },
            css = { "prettierd" },
            scss = { "prettierd" },
            yaml = { "prettierd" },
            html = { "rustywind" },
            markdown = { "rustywind" },
            lua = { "stylua" },
            java = { "google-java-format" },
            cpp = { "clang-format", "astyle" },
            c = { "clang-format", "astyle" },
            proto = { "clang-format" },
            rust = { "rustfmt" },
            go = { "goimports", "gofmt" },
            templ = { "templ" },
        },
        default_format_opts = {
            lsp_format = "fallback",
            stop_after_first = true,
        },
        notify_no_formatters = true,
    },
}
